### ISSUE TITLE
Ошибка zhimi.humidifier.ca4

### ISSUE THREAD

**Issue by krasilnikovao** [stason325/node-red-contrib-miio-localdevices#1]
При любом действии выдает ошибку "Mihome Exception. IP: 192.168.0.10 -> command error"

**Comment by stason325** [comment]
> При любом действии выдает ошибку "Mihome Exception. IP: 192.168.0.10 -> command error"
> 
> 

А опрашивает get-нодой нормально? Выдаёт полный json характеристик?

**Comment by krasilnikovao** [comment]
Да в дебаг приходит msg: 
{"_msgid":"636db1cf01af4785","name":"Увлажнитель - Кухня","address":"192.168.0.10","model":"zhimi.humidifier.ca4","polling":"ON. Every 30 sec"}

**Comment by stason325** [comment]
> Да в дебаг приходит msg: 
> 
> {"_msgid":"636db1cf01af4785","name":"Увлажнитель - Кухня","address":"192.168.0.10","model":"zhimi.humidifier.ca4","polling":"ON. Every 30 sec"}

А в msg.payload характеристики есть?

**Comment by krasilnikovao** [comment]
Нет это все тело msg

**Comment by stason325** [comment]
> Нет это все тело msg

Попробуйте удалить гет-ноду, сделать фул деплой, затем ещё раз ее создать. Не включайте auto-polling (снимите галку) и единоразово закиньте в новую гет-ноду метку времени. На выходе в msg.payload должны выскочить все характеристики устройства.


Если все получится, то не включайте пока auto-polling. В новой версии я механизм немного переделаю.

**Comment by krasilnikovao** [comment]
Та же самая история
{"_msgid":"6f315af68636bd2a","name":"Humi - Kitchen","address":"192.168.0.10","model":"zhimi.humidifier.ca4","polling":"OFF"}

**Comment by stason325** [comment]
> Та же самая история
> 
> {"_msgid":"6f315af68636bd2a","name":"Humi - Kitchen","address":"192.168.0.10","model":"zhimi.humidifier.ca4","polling":"OFF"}

Тогда ещё NR нужно попробовать рестартануть.
А все параметры девайса точно правильные? токен, ip-адрес?

**Comment by krasilnikovao** [comment]
> Тогда ещё NR нужно попробовать рестартануть.
> А все параметры девайса точно правильные? токен, ip-адрес?

Рестартовал NR
Параметры несколько раз проверил перед тем как issue писать

**Comment by stason325** [comment]
> > Тогда ещё NR нужно попробовать рестартануть.
> 
> > А все параметры девайса точно правильные? токен, ip-адрес?
> 
> 
> 
> Рестартовал NR
> 
> Параметры несколько раз проверил перед тем как issue писать
> 
> 

Именно после отключения auto-poll нужно рестарт сделать.
Сейчас такое ощущение, что нода не видит ваш девайс.
Как только получится его пнуть и ответ получить с характеристиками, можно команды уже тестировать.

**Comment by krasilnikovao** [comment]
> > > Тогда ещё NR нужно попробовать рестартануть.
> > 
> > 
> > > А все параметры девайса точно правильные? токен, ip-адрес?
> > 
> > 
> > Рестартовал NR
> > Параметры несколько раз проверил перед тем как issue писать
> 
> Именно после отключения auto-poll нужно рестарт сделать. Сейчас такое ощущение, что нода не видит ваш девайс. Как только получится его пнуть и ответ получить с характеристиками, можно команды уже тестировать.

Поднял Node.js + node-mihome ошибка в данной библиотеке она ждет сообщение длинной 33 байта, а устройство в первом же сообщении присылает только 32 байта 
![CleanShot 2022-01-31 at 05 15 24@2x](https://user-images.githubusercontent.com/64443514/151723990-559bf357-1bb8-4735-adea-a9044725ef4f.png)

**Comment by krasilnikovao** [comment]
Ошибка в библиотеке node-mihome, при инициализации устройства всегда происходит запрос параметров вот как раз на нем и происходит ошибка в запросе get_prop

**Comment by stason325** [comment]
> Ошибка в библиотеке node-mihome, при инициализации устройства всегда происходит запрос параметров вот как раз на нем и происходит ошибка в запросе get_prop

Теперь уже более понятно.
get_prop - это базовая универсальная команда для опроса устройства. Если она завершилась неудачей, то значит не было найдено устройство заданой модели по заданному IP-адресу с заданным Токеном.
Эта команда используется во всех библиотеках, использующих локальный протокол MIIO. Не только в node-mihome, но и в Miio, и в pymiio.

Что могу посоветовать:
- опросить еще раз токен экстрактором вашу учетную запись MiHome и оттуда взять текущие актуальные параметры устройства, привязанного к вашей учётке: модель, IP-адрес и токен
- в настройках роутера задать для вашего устройства статический IP

Возможно увлажнитель выдергивался из сети и мог поменяться IP или токен.

И пока не используйте auto-polling до апдейта ноды.

**Comment by krasilnikovao** [comment]
> * опросить еще раз токен экстрактором вашу учетную запись MiHome и оттуда взять текущие актуальные параметры устройства, привязанного к вашей учётке: модель, IP-адрес и токен

Пересоздал устройство в mihome, получил новый токен экстрактором

> * в настройках роутера задать для вашего устройства статический IP

Задал стат ip на роутере
Все равно тоже история:  устройство отвечает, но выдает ответ "Command error"
Но вот если заведомо указать неверный токен тогда приходит ошибка "Call to device timed out", устройство в принципе не отвечает если неверный токен

**Comment by krasilnikovao** [comment]
Скорее всего тогда ошибка или в node-mihome, или же совсем локальная у меня, поэтому я думаю можно закрыть ишью. Спасибо.

**Comment by stason325** [comment]
> Все равно тоже история: устройство отвечает, но выдает ответ "Command error"

Если устройство отвечает и гет-нода выдает в дебаге msg.payload весь json характеристик  - это уже хорошо. Значит опозналось.
С управляющими командами давай тоже попробуем решить.

Давайте потестируем на команде power. Попробуйте посылать в нее посылать в нее не true/false, а например стринговые "on" и "off".
Если сработает, то надо проверить каждую поддерживаемую команду и на предмет правильного значения:
вот definition file по вашему устройству https://github.com/maxinminax/node-mihome/blob/master/lib/devices/zhimi.humidifier.ca4.js

После теста, я тогда описание в devices.md поменяю

**Comment by MaksimShakavin** [comment]
У меня такая же ошибка, только гет нода не возвращает список команд. IP точно верный, токен тоже.

**Comment by stason325** [comment]
Ребят, в обновленной версии поддержка девайса добавлена и рабочая на основании тестов. DefFile новый теперь нужно копировать в папку либы, как выяснилось, девайс MIOT. Вся обвязка в версии 0.5.11 сделана.
Enjoy!
