### ISSUE TITLE
Error "Model dmaker.fan.p18 is not supported"

### ISSUE THREAD

**Issue by mema0007** [stason325/node-red-contrib-miio-localdevices#11]
I get the error "Model dmaker.fan.p18 is not supported". The node MIIOgetdata sends no messages and after sending a message to the node MIIOsencommand the state under the node is permanent "Connecting...".

**Comment by stason325** [comment]
Hi, it seems that you forgot to copy-paste the definition file according to instructions in readme. Please, copy-paste the file, reboot NR after that and try again to poll the device.

**Comment by mema0007** [comment]
Hi, of course you are right, i was blind. After adding the file it works now fine with the fan as well as before with the humidifier.
Many Thanks!

**Comment by stason325** [comment]
> Hi, of course you are right, i was blind. After adding the file it works now fine with the fan as well as before with the humidifier.
> 
> Many Thanks! 

It's really nice to hear that my nodes work fine for your purposes😊

**Comment by mema0007** [comment]
Your nodes were one part of the decision to buy the fan, the other was the great energy efficiency. I like same devices from Xiaomi but not to use the cloud and the app.
