### ISSUE TITLE
empty payload

### ISSUE THREAD

**Issue by TheNON75** [stason325/node-red-contrib-miio-localdevices#19]
Hello,

i have a zhimi.humidifier.ca4
- configured cloud access with default polling
- obtained and provided ip/token
- etc.

the payload is empty.
Please, inform me what additional information is needed.

(I saw there was an issue in this regards but the whole conversation is in cyrillic letters which i do not understand)

thanks

**Comment by stason325** [comment]
Hello.
The overall result of that conversation was that starting from 0.5.11 defFile for that device was updated (based on MIOT protocol) and tested.

Make sure that you have copy-pasted defFile to target folder according to readme. This solves 99% of the problems according to my experience.

As for cloud auth - it turned out that it doesn't give any profit in connection to the device. I'm planning to delete that option.

Regards

**Comment by TheNON75** [comment]
Thanks for the reply.
I am on the latest version 0.5.12
Does the def file copy make sense?

**Comment by stason325** [comment]
yes it does, because my nodes are just a sort of wrapper for node-mihome lib. The main engine is inside the lib, that's why you need to copy defFile to the target lib's folder to make node-mihome work with it.

As for version it's critical that it is >= 0.5.11

**Comment by TheNON75** [comment]
Ok, clear
- file deleted
- obtained with wget from GitHub
- nodered restarted
- send node looks better

Get node payload is still empty.
Send command has no effect if custom json. If preselected e.g. power and a Boolean false is injected, it throws an exception error.

The device is on the same vlan as nodered, the device is registered to mihome app 
Token is obtained from the mi cloud.

**Comment by stason325** [comment]
No response from get-node at all?
Try to turn on polling for say 30 seconds and click something in mihome app. Get-node should return actual JSON with props after this or after sending command through send-node

Custom JSON: be careful with spelling here (see devises.md table). It should be something like { Power: true, Buzzer: false}

**Comment by TheNON75** [comment]
Thanks, I will try it a little later.
For custom json I used in the inject as payload
- type object
- {"Power":false}

It went through the send node without issue but had no effect.

**Comment by TheNON75** [comment]
Tested: 
- get node returns no payload when the device is operated.
- Polling is enabled and set to 30 seconds, but no messages are generated

**Comment by stason325** [comment]
> Tested: 
> - get node returns no payload when the device is operated.
> - Polling is enabled and set to 30 seconds, but no messages are generated 

I still think something wrong with defFile. We started from this very point when tested ca4 previous time.
Empty payload = lib doesn't see any properties = doesn't see correct defFile with properties

**Comment by stason325** [comment]
> Thanks, I will try it a little later.
> For custom json I used in the inject as payload
> - type object
> - {"Power":false}
> 
> It went through the send node without issue but had no effect.
> 
> 

Try it without the quotes

**Comment by TheNON75** [comment]
as the inject type is object, "Power" as property has to be with quotes, false is a boolean, it must be without quotes... but tried, the inject node was highlighted with a red tiangle as error.

There is no remark in the def files re to which version it is, but anyhow, the def file is 200k.
Without the def file (downloaded yesterday), the send node only had "custom object". With the file, the possible commands are listed, so unless there is something else to download in addition, I have download what was suggested (only the ca4.js)

Shall i run some debugging? if yes, what do you need?

**Comment by stason325** [comment]
> as the inject type is object, "Power" as property has to be with quotes, false is a boolean, it must be without quotes... but tried, the inject node was highlighted with a red tiangle as error.
> 
> 

Yes, You are right about key in object, but it seems that value should be in quotes too.
Look, how it worked for me
![image](https://user-images.githubusercontent.com/79136035/214639179-4a2cb9aa-0093-4833-bd68-bbb49bcb50a4.jpeg)

**Comment by stason325** [comment]
> There is no remark in the def files re to which version it is, but anyhow, the def file is 200k. Without the def file (downloaded yesterday), the send node only had "custom object". With the file, the possible commands are listed, so unless there is something else to download in addition, I have download what was suggested (only the ca4.js)
>

Let me continue with stupid questions a bit  so we can move to next step😊
You are 100% that in target (node-mihome lib) folder: `~/.node-red/node_modules/node-mihome/lib/devices` this file?
https://github.com/stason325/node-red-contrib-miio-localdevices/blob/master/defFiles/zhimi.humidifier.ca4.js
with all this code inside

**Comment by stason325** [comment]
Latest tests of ca4 with a friend of mine gave this result ![image](https://user-images.githubusercontent.com/79136035/214643357-5044a340-e794-4d93-963b-b096c1741e84.jpeg)

**Comment by TheNON75** [comment]
okay, i decided to do it from scratch and strictly followed these steps from the guide
- copied the `zhimi.humidifer.ca4.js` from `~/.node-red/node_modules/node-red-contrib-miio-localdevices/defFiles` to `~/.node-red/node_modules/node-mihome/lib/devices`
- restarted nodered
- now both get and send works

So until now it seems to be cool and fine, but send node has only custom json (yesterday I have downloaded the ca4 file from github and then the specific commands were listed, but the things did not work)

I can live with custom json as I prefer that anyway, unless you recommend to perform further steps

(there are no stupid questions on the way to a resolution, thanks very much for pointing out the possible root cause)

**Comment by stason325** [comment]
Hello,
You've closed the issue .. do the separate commands work fine for you? Or do we need to make any further tests?

Regards

**Comment by TheNON75** [comment]
Hello,
No, the separate commands do not appear, only the custom object.

In the first attempt, which didn't work:
- downloaded the 200k file, to "your" node's deffile folder then the separate commands appeared, but didn't work
- then copied the 200k file to the other folder as specified, but didn't work

The second attempt was from scratch:
- copied the small file from deffile to the other folder
- everything works, except the separate commands, but I am happy with the custom object

We can do some more tests if you'd like, but as said, I am happy.

One small note, the water level is inaccurate it should be divided by 1.2 as max water level is 120 and not 100, but I can handle it in my flow.

Furthermore, I am missing the "target speed" and "clean mode". For instance this exists in other miio solutions
