### ISSUE TITLE
can't configure zhimi.humidifier.ca4

### ISSUE THREAD

**Issue by veneris1991** [stason325/node-red-contrib-miio-localdevices#24]
Hi! I can't configure zhimi.humidifier.ca4. I attach screenshots. Asking for help, what am I doing wrong
![1](https://user-images.githubusercontent.com/15684695/218256466-50b520e1-7624-40bf-bceb-1b97a1b2a2e5.PNG)
![2](https://user-images.githubusercontent.com/15684695/218256468-e5c14b46-8775-464a-b0ef-2cc0c0ff9a20.PNG)
![3](https://user-images.githubusercontent.com/15684695/218256469-363bb5b8-e206-4299-a5bf-87b2e7c9be3a.PNG)

**Comment by stason325** [comment]
Hi,
I guess you haven't copied updated defFile from my nodes' folder to lib's target folder.
Please follow the instructions in readme and refer to issues #1 and #19

Regards

**Comment by veneris1991** [comment]
Вы оказались правы. Всё получилось. Спасибо! Хорошего дня
