### ISSUE TITLE
Air Purifier Call to device Timeout

### ISSUE THREAD

**Issue by drschnalli** [stason325/node-red-contrib-miio-localdevices#3]
Hey there, i just installed node red and also installed this very nice plugin! 

I set up my Air Purifier 3H got the Token as described and also entered the ip (by the way what to enter for mi_id ??)

When i click deploy the Get Data Node says connection okay but when i try to send the power command via the command i see following information in the debug console:

`Mihome Exception. IP: 192.168.178.2xx-> request to https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:air-purifier:0000A007:zhimi-mb3:2 failed, reason: getaddrinfo EBUSY miot-spec.org`

and

`Mihome Exception. IP: 192.168.178.2xx -> Call to device timed out`

By the way i just found out when i use the Cloud Option... then it works fine.. but would be nice to get it working without cloud :(

**Comment by stason325** [comment]
Hello there. It's nice you are using my nodes.

Concerning mi_id you can put there random 3-digit number.

**Comment by drschnalli** [comment]
A friendly guy from the symcon forum told me to just restart node-red again after doing changes... i dont know why ( i did it before) but now it works... i disabled the Cloud button and i also rescricted internet access for the air purifier -> AND IT WORKS <3 ... so its not an issue of your perfect node! Thank you and sorry for taking your time!

**Comment by stason325** [comment]
> A friendly guy from the symcon forum told me to just restart node-red again after doing changes... i dont know why ( i did it before) but now it works... i disabled the Cloud button and i also rescricted internet access for the air purifier -> AND IT WORKS <3 ... so its not an issue of your perfect node! Thank you and sorry for taking your time!

I'm glad that everything works for you :)
Sometimes simple reboot could cure things.
