### ISSUE TITLE
Support for Mi Smart Standing Fan 2 Lite

### ISSUE THREAD

**Issue by kiclaw** [stason325/node-red-contrib-miio-localdevices#5]
Hi,
is there any chance to support Mi Smart Standing Fan 2 Lite (also known as 1C)? The model name is dmaker.fan.1c. It doesn't work with any of the built-in models.

**Comment by stason325** [comment]
> Hi,
> is there any chance to support Mi Smart Standing Fan 2 Lite (also known as 1C)? The model name is dmaker.fan.1c. It doesn't work with any of the built-in models.

Hello there.
Fans are in trend =)
I will make some research about that model and come back with a feedback

**Comment by stason325** [comment]
> Hi,
> 
> is there any chance to support Mi Smart Standing Fan 2 Lite (also known as 1C)? The model name is dmaker.fan.1c. It doesn't work with any of the built-in models.

Hello again.
I wonder whether you succeeded with testing your fan with new 0.5.8 version of the nodes?

**Comment by kiclaw** [comment]
Hi Stason, thanks for help.
Unfortunately not exactly. I copied the defFile as instructed, rebooted NR and prepared such a test flow:
![obraz](https://user-images.githubusercontent.com/64547951/174585785-14c160a2-47e9-4d33-902e-ebecfc7863cc.png)
Looks good at the beginning:
![obraz](https://user-images.githubusercontent.com/64547951/174586176-0ff5787e-32ca-4518-b6be-544306655e11.png)
so the fan's state is visible, but testing the functions gives me result "Mihome Exception. IP: 192.168.0.183 -> Could not perform operation". Maybe I should modify the inject nodes somehow?

**Comment by stason325** [comment]
> so the fan's state is visible, but testing the functions gives me result "Mihome Exception. IP: 192.168.0.183 -> Could not perform operation". Maybe I should modify the inject nodes somehow?

Hi there

Yes, you need to modify inject nodes to operate your device correctly. Please see **Devices.md** table (column _"Values for Commands"_) to choose what value to use in each inject node for each send-command node.

Regards

**Comment by kiclaw** [comment]
Ok, so I need a while to improve my NR knowledge :) Do I neet to use function node?

**Comment by stason325** [comment]
> Is it correct?
> ![obraz](https://user-images.githubusercontent.com/64547951/174611548-e158f19e-d7f7-47d2-a4f2-33c2872c339e.png)

yes, like that

**Comment by kiclaw** [comment]
Still something wrong:
![obraz](https://user-images.githubusercontent.com/64547951/174621395-75d62aa0-e911-4bf6-b82c-300554d273bd.png)

**Comment by stason325** [comment]
> Still something wrong:
> ![obraz](https://user-images.githubusercontent.com/64547951/174621395-75d62aa0-e911-4bf6-b82c-300554d273bd.png)

Once again: please, read more carefully **Devices.md** table (column _"Values for Commands"_). It's written there, that right value for for "Power" command is **true**... not "Power:true".

Just follow the instructions in readme and devices.md

**Comment by stason325** [comment]
> > Still something wrong:
> > ![obraz](https://user-images.githubusercontent.com/64547951/174621395-75d62aa0-e911-4bf6-b82c-300554d273bd.png)
> 
> Once again: please, read more carefully **Devices.md** table (column _"Values for Commands"_). It's written there, that right value for "Power" command is **true** or **false**... not "Power:true".
> 
> Just follow the instructions in readme and devices.md

**Comment by kiclaw** [comment]
Now I got it! It works, thanks.
