### ISSUE TITLE
zhimi.airpurifier.mb3 Fan Speed

### ISSUE THREAD

**Issue by Tazintosh** [stason325/node-red-contrib-miio-localdevices#7]
Hi folks,

I'm setting up my Mi Air Purifier 3H (zhimi.airpurifier.mb3) with your contrib + the HomeKit one.
Based on my understanding of the Fan_Speed related to the Mode, here's a summary:

| Mode                | Fan_Speed                                  |
|---------------------|--------------------------------------------|
| 0 (Auto)            | cannot be set                              |
| 1 (Night)           | cannot be set                              |
| 2 (Favorite/Manual) | Slider from 0 to 100% on Xiaomi's Home App |
| 3 (Level n)         | From 1 to 3 (25% to 75%)                   |

HomeKit allows (as Xiaomi's Home App) to use a 0-100% slider to set up the "RotationSpeed", but I cannot (or don't know how) set back for instance 95% using your contrib.
At the moment, I'm doing a basic conversion like: msg.payload = msg.payload.RotationSpeed * 4 / 100 and plug this to the Fan Level of MIIOsendcommand node.

How could I set any custom speed value?
When I was using [miiocli](https://python-miio.readthedocs.io/en/latest/), I was able to setup the speed based on 14 levels.

`"miiocli airpurifier --ip XXX.XXX.XXX.XXX --token someToken set_favorite_level " + Math.round(14 * rotationSpeed / 100);`

Thanks in advance for your guidance.

**Comment by stason325** [comment]
> Hi folks,
> 
> I'm setting up my Mi Air Purifier 3H (zhimi.airpurifier.mb3) with your contrib + the HomeKit one. Based on my understanding of the Fan_Speed related to the Mode, here's a summary:
> 
> Mode	Fan_Speed
> 0 (Auto)	cannot be set
> 1 (Night)	cannot be set
> 2 (Favorite/Manual)	Slider from 0 to 100% on Xiaomi's Home App
> 3 (Level n)	From 1 to 3 (25% to 75%)
> HomeKit allows (as Xiaomi's Home App) to use a 0-100% slider to set up the "RotationSpeed", but I cannot (or don't know how) set back for instance 95% using your contrib. At the moment, I'm doing a basic conversion like: msg.payload = msg.payload.RotationSpeed * 4 / 100 and plug this to the Fan Level of MIIOsendcommand node.
> 
> How could I set any custom speed value? When I was using [miiocli](https://python-miio.readthedocs.io/en/latest/), I was able to setup the speed based on 14 levels.
> 
> `"miiocli airpurifier --ip XXX.XXX.XXX.XXX --token someToken set_favorite_level " + Math.round(14 * rotationSpeed / 100);`
> 
> Thanks in advance for your guidance.

Hi there.
Basically zhimi.airpurifier.mb3 is supported natively in my contrib: it means that I didn't updated the definition file for that device and used the default file that is inside node-mihome library. 
But now I've looked through the Xiaomi specs (here is the link for specs: https://home.miot-spec.com/spec/zhimi.airpurifier.mb3) and see that mb3 additionally to existing commands supports such commands as:
"favorite_level" (0-14): {"siid": 10, "piid": 10} ,
"favorite_rpm" (300-2300): {"siid": 10, "piid": 7},
"motor_speed" (0-3000): {"siid": 10, "piid": 8}.

_What I propose then:_ I will update defFile and add these commands in next version 0.5.9. Then you can make tests and give me some feedback after that. Hopefully your conversion could become simpler as you can convert directly between Mi's "motor-speed" and HK's "RotationSpeed".
**One more important thing here**: after updating please don't forget to follow the instructions of copy-pasting new defFile (please see here https://github.com/stason325/node-red-contrib-miio-localdevices#send-node - point 3).

I  will try to release the update lately today or tomorrow.

Regards

**Comment by Tazintosh** [comment]
Thanks for the answer!
I'll for sure give you feedback, cannot guaranty I'll be as fast as you though.

**Comment by stason325** [comment]
> Thanks for the answer!
> I'll for sure give you feedback, cannot guaranty I'll be as fast as you though.

Hello again. 
Nodes are updated to version 0.5.9, enjoy testing and don't forget to copy-paste new defFile (please see https://github.com/stason325/node-red-contrib-miio-localdevices#send-node - point 3).

Regards

**Comment by Tazintosh** [comment]
Thank you!
I've tested it and it's working!
Note that it looks like the maximum favorite speed my fav can reach is 2150 (when pushing the slider at max in Xiaomi Home app and looking back in Node-RED the Get node log.

**Comment by stason325** [comment]
> Thank you!
> 
> I've tested it and it's working!
> 
> Note that it looks like the maximum favorite speed my fav can reach is 2150 (when pushing the slider at max in Xiaomi Home app and looking back in Node-RED the Get node log.

It is interesting, because specs give us info that maximum reachable speed is 2300.

https://home.miot-spec.com/spec/zhimi.airpurifier.mb3
See siid 10, piid 7

But still it's working now and this is good👍🏻
Could we close the issue then?
