### ISSUE TITLE
zhimi.airpurifier.vb2 support

### ISSUE THREAD

**Issue by Atalicsku** [stason325/node-red-contrib-miio-localdevices#9]
Thanks for this module

Could you add Mi Air Purifier Pro H as supported device?

Br,
Attila

**Comment by stason325** [comment]
> Thanks for this module
> 
> Could you add Mi Air Purifier Pro H as supported device?
> 
> Br, Attila

Hi, Attila.

zhimi.airpurifier.vb2 is already supported via my nodes.
Please see https://github.com/stason325/node-red-contrib-miio-localdevices/blob/master/DEVICES.md

When configuring and testing usage follow the instructions in readme and don't forget to copy-paste defFile for your purifier (please pay attention on point 3 here: https://github.com/stason325/node-red-contrib-miio-localdevices#send-node)

Regards,
Stas

**Comment by Atalicsku** [comment]
Thank you. That was a problem.
Connection appears OK and disappear.
I get back the msg. The payload is empty.
I am doing something wrong...

**Comment by stason325** [comment]
> Thank you. That was a problem.
> 
> Connection appears OK and disappear.
> 
> I get back the msg. The payload is empty.
> 
> I am doing something wrong...

Did you copy-paste the defFile to target folder and reboot NR after that?

**Comment by Atalicsku** [comment]
> > Thank you. That was a problem.
> > Connection appears OK and disappear.
> > I get back the msg. The payload is empty.
> > I am doing something wrong...
> 
> Did you copy-paste the defFile to target folder and reboot NR after that?

yes

**Comment by Atalicsku** [comment]
> > > Thank you. That was a problem.
> > > Connection appears OK and disappear.
> > > I get back the msg. The payload is empty.
> > > I am doing something wrong...
> > 
> > 
> > Did you copy-paste the defFile to target folder and reboot NR after that?
> 
> yes

not supported message missed

**Comment by stason325** [comment]
> not supported message missed

Could you share some pictures of debug messages from get-node and send-nodes after sending some basic commands?

Need to understand what goes wrong...

**Comment by Atalicsku** [comment]
> > not supported message missed
> 
> Could you share some pictures of debug messages from get-node and send-nodes after sending some basic commands?
> 
> Need to understand what goes wrong...

![image](https://user-images.githubusercontent.com/15057915/176955494-c350ab99-977e-42e7-b649-b0d538d4b1a5.png)

**Comment by stason325** [comment]
> > > not supported message missed
> 
> > 
> 
> > Could you share some pictures of debug messages from get-node and send-nodes after sending some basic commands?
> 
> > 
> 
> > Need to understand what goes wrong...
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/15057915/176955494-c350ab99-977e-42e7-b649-b0d538d4b1a5.png)
> 
> 

What I see is that device does not respond ... most likely it is because 1 sec auto-polling interval. You overpushed your device with too many messages and device hung, that's why you see "call to device timed out" error message.
I strongly recommend not to use less than 15 sec auto-polling interval.

For now you need to increase auto-polling interval up to say 30 secs, reboot the device and reboot NR.

After that I believe everything should go right.
Try and come back with the results.

**Comment by Atalicsku** [comment]
> > > > not supported message missed
> > 
> > 
> > > 
> > 
> > 
> > > Could you share some pictures of debug messages from get-node and send-nodes after sending some basic commands?
> > 
> > 
> > > 
> > 
> > 
> > > Need to understand what goes wrong...
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/15057915/176955494-c350ab99-977e-42e7-b649-b0d538d4b1a5.png)
> 
> What I see is that device does not respond ... most likely it is because 1 sec auto-polling interval. You overpushed your device with too many messages and device hung, that's why you see "call to device timed out" error message. I strongly recommend not to use less than 15 sec auto-polling interval.
> 
> For now you need to increase auto-polling interval up to say 30 secs, reboot the device and reboot NR.
> 
> After that I believe everything should go right. Try and come back with the results.

Shit. :) Right. That was the problem. It is working. I saw before a normal payload so I do not understand what was the problem.
Thank you very well.

**Comment by stason325** [comment]
That's ok.
It is great that issue was minor and easily solved 👍🏻
